services:
  metastore:
    image: postgres:11
    container_name: postgres
    hostname: metastore
    environment:
      POSTGRES_DB: hive
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3      
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./base/ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      minilake-net:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "historyserver:172.28.1.5"

  master:
    image: ahmad/minilake-master:hadoop331
    container_name: master-node
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3 
    ports:
      - "4040:4040"
      - "4044:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
      - "7077:7077"
    volumes:
      - namenode:/opt/hadoop/dfs/name
    restart: always
    networks:
      minilake-net:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "historyserver:172.28.1.5"

  worker1:
    image: ahmad/minilake-worker:hadoop331
    container_name: worker-node1
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3 
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
    restart: always
    networks:
      minilake-net:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "historyserver:172.28.1.5"

  # worker2:
  #   image: ahmad/minilake-worker:hadoop331
  #   container_name: worker-node2
  #   hostname: worker2
  #   depends_on:
  #     - master
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.1.2
  #     SPARK_LOCAL_IP: 172.28.1.4
  #     SPARK_LOCAL_HOSTNAME: worker2
  #     PYSPARK_PYTHON: /opt/conda/bin/python3
  #     PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3 
  #   ports:
  #     - "8043:8042"
  #     - "8082:8081"
  #     - "9865:9864"
  #   volumes:
  #     - datanode2:/opt/hadoop/dfs/data
  #   restart: always
  #   networks:
  #     minilake-net:
  #       ipv4_address: 172.28.1.4
  #   extra_hosts:
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "historyserver:172.28.1.5"

  historyserver:
    image: ahmad/minilake-history:hadoop331
    container_name: historyserver
    hostname: historyserver
    depends_on:
      - master
      - worker1
      # - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: historyserver
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3 
    ports:
      - "18080:18080"
      - "19888:19888"
    restart: always
    networks:
      minilake-net:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"

  jupyter:
    image: ahmad/minilake-jupyter:hadoop331
    container_name: jupyter-node
    hostname: root
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.6
      SPARK_LOCAL_HOSTNAME: root
      PYSPARK_PYTHON: /opt/conda/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/conda/bin/python3 
    depends_on:
      - master
      - worker1
      # - worker2
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
    restart: always
    networks:
      minilake-net:
        ipv4_address: 172.28.1.6
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "historyserver:172.28.1.5"
  
  # # HUE (Management node, similar to Ambari)
  # hue:
  #   container_name: hue
  #   image: gethue/hue:4.4.0
  #   ports:
  #     - 8000:8888
  #   env_file:
  #     - ./hadoop.env
  #   volumes:
  #     - ./hue/hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
  #   depends_on:
  #     - master
  #     - historyserver
  #   networks:
  #     - minilake-net

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:

networks:
  minilake-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
